// src/App.tsx
import { HashRouter as Router, Routes, Route, Link } from "react-router";
import packageJson from '../package.json';

import Learn from './pages/Learn/Learn';
import Admin from './pages/Admin/Admin';
import About from './pages/About/About';
import Settings from './pages/Settings/Settings';
import NotFound from './pages/NotFound/NotFound';

function App() {
  return (
    <Router>
      <div className="app">
        <div className="app__header">
        <nav>
          <ul>
            <li><Link to="/">Learn</Link></li>
            <li><Link to="/admin">Admin</Link></li>
            <li><Link to="/about">About</Link></li>
            <li><Link to="/settings">Settings</Link></li>
          </ul>
        </nav>
        </div>

        <div className="app__content">

          <Routes>
            <Route path="/" element={<Learn />} />
            <Route path="/admin" element={<Admin />} />
            <Route path="/about" element={<About />} />
            <Route path="/settings" element={<Settings />} />
            <Route path="*" element={<NotFound />} />
          </Routes>

        </div>
      </div>

      <div className="version">{packageJson.version}</div>
    </Router>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import Router, { link } from 'svelte-spa-router';
  import packageJson from '../package.json';
  import Learn from './pages/Learn.svelte';
  import Admin from './pages/Admin.svelte';
  import About from './pages/About.svelte';
  import Settings from './pages/Settings.svelte';
  import NotFound from './pages/NotFound.svelte';

  const routes = {
    '/': Learn,
    '/admin': Admin,
    '/about': About,
    '/settings': Settings,
    '*': NotFound,
  };
</script>


<div class="app">
  <div class="app__header">
    <nav>
      <ul>
        <li><a href="/" use:link>Learn</a></li>
        <li><a href="/admin" use:link>Admin</a></li>
        <li><a href="/about" use:link>About</a></li>
        <li><a href="/settings" use:link>Settings</a></li>
      </ul>
    </nav>
  </div>

  <div class="app__content">
    <Router {routes} />
  </div>
</div>

<div className="version">{packageJson.version}</div>
